# GENERATED by scripts/print_extraction_vocab.py -- do not hand-edit.
# Source: graph_cache.pkl. 46 kinds, 20 units.
# Every phrasing is the MUTCD's own wording with all numbers removed,
# so there is no threshold for the model to answer with.
KIND_PHRASING = {
  'ANGLE': 'If the signs are mounted at an angle of',
  'BORDER': 'A border for -inch signs with a light background should be from',
  'BUFFER': 'Where a buffer space is more than',
  'CLEARANCE': 'C. Having a roadway horizontal clearance of',
  'COUNT_PEOPLE': '* A high-occupancy bus is defined as a bus occupied by at least',
  'COUNT_SCHOOLCHILDREN': 'ldren are using the crossing is less than the number of minutes in the same period and there are a minimum of',
  'DELAY_VEHICLE_HOURS': 'controlled by a STOP sign equals or exceeds: vehicle-hours for a one-lane approach or',
  'DEPTH': 'should be used when an unprotected shoulder drop-off, adjacent to the travel lane, exceeds',
  'DIAMETER': 'For -inch diameter light units, the light centers shall be spaced approximately',
  'DISTANCE': 'The maximum distance should be',
  'DURATION': 'B. Intermediate-expected duration of',
  'HEIGHT': 'Where the sign is mounted at a height of',
  'INTERVAL': '* The countdown display is optional for Pedestrian Change Intervals of',
  'LANES': 'Phase A-two travel lanes northbound and',
  'LENGTH': 'When rail lengths are less than',
  'LETTER_HEIGHT': 'Using letter heights of more than',
  'MOUNTING_HEIGHT': 'Mounting height shall be at least',
  'PITCH': 'The application of LEDs to display sign legends or symbols shall use a maximum pitch of',
  'POPULATION': 'easures when the major-street speed exceeds mph or in an isolated community with a population of less than',
  'RADIUS': 'ne at all times that a pedestrian is present within a',
  'REDUCTION': 'The minimum lane reduction transition taper length should be',
  'RETROREFLECTIVITY': 'this table are in units of cd/lx/m2 measured at an observation angle of degrees and an entrance angle of',
  'SIGHT_DISTANCE': 'The passing sight distance on a vertical curve is the distance at which an object',
  'SIZE': 'Secondary symbols of a smaller size (',
  'SPACING': 'If the signal spacing is less than',
  'SPEED_85TH': 'See for approaches with posted, statutory, or 85th-percentile speeds of',
  'SPEED_ADVISORY': 'should be used instead of a Curve sign in advance of a horizontal curve that has an advisory speed of',
  'SPEED_ALTERNATIVES': 'A. The posted or statutory speed limit on the approach is',
  'SPEED_AVERAGE': "",   # no clean example in the manual
  'SPEED_CHANGE': 'Where restrictive features justify a speed reduction of more than',
  'SPEED_DESIGN': 'If the design speed of the curves is',
  'SPEED_DIFFERENTIAL': 'evices for Changes in Horizontal Alignment Speed Differential3 Devices for Change in Horizontal Alignment3',
  'SPEED_LIMIT': 'For roadways having a speed limit of',
  'SPEED_LIMIT_POSTED': 'Where the posted speed limit is',
  'SPEED_LIMIT_STATUTORY': "",   # no clean example in the manual
  'SPEED_OPERATING': 'On roadways with operating speeds less than',
  'SPEED_PACE': "",   # no clean example in the manual
  'SPEED_PEDESTRIAN': 'd 4J- may be reduced as much as percent if the 15th-percentile crossing speed of pedestrians is less than',
  'SPEED_PREVAILING': "",   # no clean example in the manual
  'SPEED_TRAIN': 'Where trains are permitted to travel at speeds exceeding',
  'SPEED_UNRESOLVED': 'On low-volume roads with speeds of',
  'TAPER': 'The minimum taper length should be',
  'VOLUME': 'Automatic volume adjustment up to a maximum volume of',
  'VOLUME_DAILY': 'Where the sum of exit volumes is estimated to be lower than',
  'VOLUME_HOURLY': 'The volume on the same minor-street approach equals or exceeds',
  'WIDTH': 'Minimum crosswalk width shall be',
}

KINDS = sorted(KIND_PHRASING) + ["OTHER"]
UNITS = ['count', 'days', 'degrees', 'feet', 'feet per second', 'hours', 'inches', 'lanes', 'miles', 'millimeters', 'minutes', 'months', 'mph', 'people', 'percent', 'seconds', 'vehicle-hours', 'vehicles per day', 'vehicles per hour', 'years']

print(len(KINDS), "kinds,", len(UNITS), "units")
